export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';

export const CHANGE_LAYOUT_START = 'CHANGE_LAYOUT_START';
export const CHANGE_LAYOUT_SUCCESS = 'CHANGE_LAYOUT_SUCCESS';
export const CHANGE_LAYOUT_FAILURE = 'CHANGE_LAYOUT_FAILURE';

export const SAVE_IMAGES_START = 'SAVE_IMAGES_START';
export const SAVE_IMAGES_SUCCESS = 'SAVE_IMAGES_SUCCESS';
export const SAVE_IMAGES_FAILURE = 'SAVE_IMAGES_FAILURE';

export const DELETE_IMAGE_START = 'DELETE_IMAGE_START';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE';

export const SHOW_MORE_IMAGES_START = 'SHOW_MORE_IMAGES_START';
export const SHOW_MORE_IMAGES_SUCCESS = 'SHOW_MORE_IMAGES_SUCCESS';
export const SHOW_MORE_IMAGES_FAILURE = 'SHOW_MORE_IMAGES_FAILURE';