export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';

export const SAVE_IMAGES_START = 'SAVE_IMAGES_START';
export const SAVE_IMAGES_SUCCESS = 'SAVE_IMAGES_SUCCESS';
export const SAVE_IMAGES_FAILURE = 'SAVE_IMAGES_FAILURE';